[pytest]
# Tell pytest where tests live
testpaths = tests

# Add the repository root so imports such as src.cleaning_customers work.
pythonpath = .

# Ignore PySpark + Deprecation warnings
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning

# Disable noisy warnings
addopts = --disable-warnings
