[pytest]
# Tell pytest where tests live
testpaths = tests

# Add src to PYTHONPATH automatically
pythonpath = src

# Ignore PySpark + Deprecation warnings
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::pyspark.sql.utils.AnalysisException

# Disable noisy warnings
addopts = --disable-warnings
